# Change these first
owner: tjcsl # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Ion
    url: https://ion.tjhsst.edu
    maxResponseTime: 2000

  - name: Director
    url: https://director.tjhsst.edu
    maxResponseTime: 2000
  
  - name: Webmail
    url: https://webmail.tjhsst.edu
    maxResponseTime: 2000

  - name: Jupyterhub
    url: https://jupyterhub.tjhsst.edu
    maxResponseTime: 2000

  - name: Othello
    url: https://othello.tjhsst.edu
    maxResponseTime: 2000

  - name: Tiny (URL shortner)
    url: https://tiny.tjhsst.edu
    maxResponseTime: 2000

  - name: SSO (Authentication)
    url: https://sso.tjhsst.edu
    maxResponseTime: 2000

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.tjhsst.edu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars1.githubusercontent.com/u/5313020
  name: CSL Status
  introTitle: "TJHSST Computer Systems Lab Status"
  introMessage: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
